"""Real browser group firewall cases; synthetic fixtures and network disabled."""
import asyncio,json,os
from pathlib import Path
from playwright.async_api import async_playwright,expect
ROOT=Path(__file__).resolve().parents[1]
CORE=Path(os.environ['HERMES_SOURCE'])
async def main():
    async with async_playwright() as p:
        browser=await p.chromium.launch(headless=True)
        page=await browser.new_page(viewport={'width':1440,'height':1000})
        await page.route('**/*',lambda route:route.abort())
        errors=[];page.on('pageerror',lambda e:errors.append(str(e)))
        await page.set_content('<!doctype html><html lang="pt-BR"><body><div id="root"></div></body></html>')
        for css in (CORE/'hermes_cli/web_dist/assets').glob('*.css'): await page.add_style_tag(content=css.read_text())
        await page.add_style_tag(content=':root{--background:#041c1c;--midground:#ffe6cb;--theme-font-sans:system-ui}html,body,#root{height:auto!important;overflow:visible!important}body{background:var(--background);color:var(--midground)}')
        await page.add_style_tag(path=str(ROOT/'dashboard/dist/style.css'))
        await page.add_script_tag(path=os.environ['RYZE_UI_HARNESS'])
        await page.evaluate("window.testSeed({credential_saved:true,instance:'hermes-demo',allowed_users:'5511999999999',allowed_recipients:'5511999999999',buffer_seconds:20,echo_transcripts:true,enabled:true,webhook_configured:true});window.testConnected()")
        await page.add_script_tag(path=str(ROOT/'dashboard/dist/index.js'))
        async def tab(name): await page.get_by_role('navigation',name='Navegação RyzeAPI').get_by_role('button',name=name,exact=True).click()
        await tab('Configurações')
        groups=page.locator('.ryze-groups')
        await expect(groups).to_contain_text('Nenhum grupo no catálogo')
        await groups.get_by_role('button',name='Listar / sincronizar grupos').click()
        await expect(groups.locator('article')).to_have_count(0)
        search=groups.locator('#ryze-group-search')
        await search.click()
        await expect(groups.get_by_role('option')).to_have_count(1)
        await search.press('ArrowDown');await search.press('Enter')
        await expect(groups.locator('.ryze-group-box .ryze-group-chip')).to_have_count(1)
        await expect(search).to_have_attribute('aria-expanded','false')
        row=groups.locator('article').first
        await expect(row).to_contain_text('Salvo: Bloqueado')
        await row.get_by_label('Modo do grupo:',exact=False).select_option('respond')
        await row.get_by_label('Quando responder:',exact=False).select_option('all')
        await row.get_by_label('Quem pode acionar a IA:',exact=False).select_option('all')
        await expect(row).to_contain_text('qualquer membro deste grupo')
        await expect(row.get_by_role('button',name='Salvar grupo')).to_be_disabled()
        await groups.get_by_role('button',name='Listar / sincronizar grupos').click()
        await expect(row.get_by_label('Quando responder:',exact=False)).to_have_value('all')
        await tab('Métricas');await tab('Configurações')
        await expect(groups.locator('article')).to_have_count(0)
        chip=groups.get_by_role('button',name='Editar grupo Família · exemplo sintético',exact=True)
        await chip.click()
        await expect(row.get_by_label('Quem pode acionar a IA:',exact=False)).to_have_value('all')
        await row.get_by_role('checkbox').check()
        await row.get_by_role('button',name='Salvar grupo').click()
        await expect(groups.locator('article')).to_have_count(0)
        await expect(chip).to_have_attribute('aria-expanded','false')
        await expect(chip).not_to_contain_text('Não salvo')
        await chip.click()
        await expect(row).to_contain_text('Salvo: Ouvir e responder')
        await expect(row.get_by_role('button',name='Descartar alterações')).to_have_count(0)
        await row.get_by_label('Modo do grupo:',exact=False).select_option('listen')
        await expect(row.get_by_label('Quando responder:',exact=False)).to_have_count(0)
        await row.get_by_role('button',name='Fechar edição').click()
        await expect(groups.locator('article')).to_have_count(0)
        await expect(chip).to_contain_text('Alterações não salvas')
        await expect(chip).to_be_focused()
        await chip.click()
        await expect(row.get_by_label('Modo do grupo:',exact=False)).to_have_value('listen')
        await row.get_by_role('button',name='Descartar alterações').click()
        await expect(row.get_by_label('Modo do grupo:',exact=False)).to_have_value('respond')
        await page.evaluate('window.testGroupFailure=true')
        await groups.get_by_role('button',name='Listar / sincronizar grupos').click()
        await expect(groups.get_by_role('alert')).to_contain_text('catálogo anterior foi preservado')
        await expect(row).to_contain_text('Família')
        await page.evaluate('window.testGroupFailure=false')
        await groups.get_by_role('button',name='Consultar catálogo salvo').click()
        await search.fill('inexistente')
        await expect(groups).to_contain_text('Nenhum grupo corresponde')
        await search.fill('')
        await search.press('Escape')
        # A second group is selected into the same box; only its editor is shown.
        await page.evaluate("window.testGroups.push({jid:'120363000000000002@g.us',name:'Trabalho · grupo de exemplo com nome longo para verificar quebra no celular',members:12,present:1,synced:1789488000,mode:'blocked',trigger:'mentions',senders:'authorized'})")
        await groups.get_by_role('button',name='Listar / sincronizar grupos').click()
        await search.fill('000000000002')
        await groups.get_by_role('listbox').get_by_role('option').click()
        await expect(groups.locator('.ryze-group-chip')).to_have_count(2)
        await expect(groups.locator('article')).to_have_count(1)
        await expect(row).to_contain_text('Trabalho')
        await chip.click()
        await expect(row).to_contain_text('Família')
        # X opens a dedicated confirmation, never mutates policy on first click.
        before=await page.evaluate('window.testCalls.filter(c=>c.path==="/groups/policy").length')
        await groups.get_by_role('button',name='Remover seleção de Família · exemplo sintético',exact=True).click()
        removal=groups.locator('.ryze-group-removal')
        await expect(removal).to_contain_text('Remover Família')
        await expect(groups.locator('article')).to_have_count(0)
        assert await page.evaluate('window.testCalls.filter(c=>c.path==="/groups/policy").length')==before
        await expect(groups.locator('.ryze-group-chip')).to_have_count(2)
        await removal.get_by_role('button',name='Cancelar remoção').click()
        await expect(removal).to_have_count(0)
        await expect(row.get_by_label('Modo do grupo:',exact=False)).to_have_value('respond')
        # Removal failures keep the chip and offer an in-place retry/cancel.
        await groups.get_by_role('button',name='Remover seleção de Família · exemplo sintético',exact=True).click()
        await page.evaluate('window.testGroupFailure=true')
        await removal.get_by_role('button',name='Remover e bloquear',exact=True).click()
        await expect(removal.get_by_role('alert')).to_be_visible()
        await expect(groups.locator('.ryze-group-chip')).to_have_count(2)
        assert await page.evaluate('window.testGroups[0].mode')=='respond'
        await page.evaluate('window.testGroupFailure=false')
        await removal.get_by_role('button',name='Remover e bloquear',exact=True).click()
        await expect(chip).to_have_count(0)
        await expect(removal).to_have_count(0)
        await expect(search).to_be_focused()
        assert await page.evaluate('window.testGroups[0].mode')=='blocked'
        # Remount demonstrates saved removal; unsaved second-group draft survives.
        await tab('Métricas');await tab('Configurações')
        await expect(chip).to_have_count(0)
        await expect(groups.locator('article')).to_have_count(0)
        # Removing a never-enabled draft is immediate and never calls the API.
        before=await page.evaluate('window.testCalls.filter(c=>c.path==="/groups/policy").length')
        await groups.get_by_role('button',name='Remover seleção de Trabalho',exact=False).click()
        await expect(groups.locator('.ryze-group-chip')).to_have_count(0)
        assert await page.evaluate('window.testCalls.filter(c=>c.path==="/groups/policy").length')==before
        # Removed groups stay in the catalog and can be added again.
        await search.fill('Família')
        await groups.get_by_role('option').click()
        await expect(row.get_by_label('Modo do grupo:',exact=False)).to_have_value('listen')
        await row.get_by_label('Modo do grupo:',exact=False).select_option('respond')
        await row.get_by_label('Quando responder:',exact=False).select_option('mentions')
        await row.get_by_role('checkbox').check()
        await row.get_by_role('button',name='Salvar grupo').click()
        await expect(groups.locator('article')).to_have_count(0)
        await tab('Métricas');await tab('Configurações')
        await expect(chip).to_have_count(1)
        await expect(groups.locator('article')).to_have_count(0)
        # Toggle editor from the same chip; use keyboard to reopen it.
        await chip.click();await chip.click()
        await expect(groups.locator('article')).to_have_count(0)
        await chip.focus();await page.keyboard.press('Enter')
        await expect(row).to_be_visible()
        await row.get_by_role('button',name='Fechar edição').click()
        review=Path(os.environ['RYZE_UI_REVIEW']);review.mkdir(parents=True,exist_ok=True)
        for w,h,label in [(1440,1000,'desktop'),(390,844,'mobile')]:
            await page.set_viewport_size({'width':w,'height':h})
            await page.evaluate('window.scrollTo(0,0)')
            assert await page.evaluate('document.documentElement.scrollWidth<=innerWidth')
            await page.screenshot(path=str(review/(label+'.png')),full_page=True)
            await chip.click()
            await page.evaluate('window.scrollTo(0,0)')
            await page.screenshot(path=str(review/(label+'-edit.png')),full_page=True)
            await groups.get_by_role('button',name='Remover seleção de Família · exemplo sintético',exact=True).click()
            await page.evaluate('window.scrollTo(0,0)')
            await page.screenshot(path=str(review/(label+'-remove.png')),full_page=True)
            await removal.get_by_role('button',name='Cancelar remoção').click()
            await row.get_by_role('button',name='Fechar edição').click()
        await page.set_viewport_size({'width':900,'height':1000})
        assert await page.evaluate('document.documentElement.scrollWidth<=innerWidth')
        assert not errors,errors
        print(json.dumps({'result':'PASS','scenarios':25,'page_errors':errors,'screenshots':str(review)}))
        await browser.close()
if __name__=='__main__':asyncio.run(main())
