"""Task workspace regressions; real React/Nous, synthetic API, blocked network."""
import asyncio, json, os
from pathlib import Path
from playwright.async_api import async_playwright, expect

ROOT = Path(__file__).resolve().parents[1]
CORE = Path(os.environ['HERMES_SOURCE'])

async def main():
    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=True)
        page = await browser.new_page(viewport={'width':1440,'height':1000})
        await page.route('**/*', lambda route: route.abort())
        errors = []
        page.on('pageerror', lambda e: errors.append(str(e)))
        await page.clock.install()
        async def load(seed=''):
            await page.set_content('<!doctype html><html lang="pt-BR"><head></head><body><div id="root"></div></body></html>')
            for css in (CORE/'hermes_cli/web_dist/assets').glob('*.css'):
                await page.add_style_tag(content=css.read_text())
            await page.add_style_tag(content=':root{--background:#041c1c;--midground:#ffe6cb;--theme-font-sans:system-ui}html,body,#root{height:auto!important;overflow:visible!important}body{background:var(--background);color:var(--midground)}')
            await page.add_style_tag(path=str(ROOT/'dashboard/dist/style.css'))
            await page.add_script_tag(path=os.environ['RYZE_UI_HARNESS'])
            if seed: await page.evaluate(seed)
            await page.add_script_tag(path=str(ROOT/'dashboard/dist/index.js'))
        async def click(label):
            await page.get_by_role('button', name=label, exact=True).click()
        async def tab(label):
            await page.get_by_role('navigation',name='Navegação RyzeAPI').get_by_role('button',name=label,exact=True).click()
        async def contact(n, command=False):
            await page.locator('#ryze-contact-number').fill(n)
            await click('Adicionar contato')
            if command: await page.get_by_role('checkbox',name='Comandar Hermes: '+n,exact=True).check()
        await load()
        await click('Conectar conta RyzeAPI')
        await expect(page.get_by_role('heading',name='Conecte sua conta RyzeAPI')).to_be_visible()
        await expect(page.get_by_role('button',name='Validar e continuar')).to_be_disabled()
        await page.locator('#ryze-token').fill('synthetic-token')
        await page.evaluate('window.testReject=true')
        await click('Validar e continuar')
        await expect(page.get_by_role('alert')).to_contain_text('Token recusado')
        await page.evaluate('window.testReject=false')
        await click('Validar e continuar')
        await expect(page.locator('input[type=password]')).to_have_count(0)
        await page.get_by_text('Selecionar ou criar instância para o Hermes',exact=True).click()
        await page.get_by_text('Criar uma nova instância',exact=True).click()
        await page.locator('#ryze-name').fill('hermes-ui-test')
        await expect(page.get_by_role('button',name='Criar e selecionar')).to_be_disabled()
        await page.locator('#ryze-create-ok').check()
        await click('Criar e selecionar')
        await click('Gerar QR Code')
        await expect(page.get_by_role('img')).to_be_visible()
        await page.clock.fast_forward(21000)
        await expect(page.get_by_text('Código expirado.',exact=False)).to_be_visible()
        before = await page.evaluate('window.testCalls.filter(c=>c.path==="/connection").length')
        await page.clock.run_for(125000)
        assert await page.evaluate('window.testCalls.filter(c=>c.path==="/connection").length') > before + 10
        await page.get_by_text('Conectar com código em vez de QR',exact=True).click()
        await page.locator('#ryze-pair-number').fill('5511999999999')
        await click('Gerar código de pareamento')
        await expect(page.get_by_text('ABCD-EFGH',exact=True)).to_be_visible()
        await page.evaluate('window.testConnected()')
        await page.clock.run_for(6000)
        await expect(page.locator('.ryze-connection.is-connected')).to_be_visible()
        await expect(page.get_by_text('ABCD-EFGH',exact=True)).to_have_count(0)
        await click('Configurar firewall e ativar')
        await contact('5511999999999',True)
        await contact('5511888888888')
        await page.locator('#ryze-permit').check()
        await click('Salvar sem ativar')
        await expect(page.get_by_role('status').filter(has_text='Firewall salvo')).to_be_visible()
        await page.locator('#ryze-permit').check()
        await click('Salvar e ativar Hermes')
        await expect(page.get_by_role('heading',name='Hermes habilitado neste canal')).to_be_visible()
        await page.locator('#ryze-buffer').fill('17')
        await page.clock.run_for(5500)
        await expect(page.locator('#ryze-buffer')).to_have_value('17')
        await tab('Métricas')
        await expect(page.get_by_text('Fila funcionando',exact=True)).to_be_visible()
        await expect(page.get_by_text('Ainda sem medições.',exact=False)).to_be_visible()
        await page.evaluate('window.testTransportError=true')
        await page.clock.run_for(5500)
        await expect(page.get_by_text('Não foi possível consultar o diagnóstico.',exact=False)).to_be_visible()
        await tab('Visão geral')
        await expect(page.locator('.ryze-channel')).to_contain_text('Estado não confirmado')
        await tab('Configurações')
        await expect(page.locator('#ryze-buffer')).to_have_value('17')
        await expect(page.get_by_role('heading',name='Hermes habilitado neste canal')).to_be_visible()
        await page.evaluate('window.testTransportError=false;window.testTransport={...window.testTransport,native_activity:{known:true,agent_tasks:2},timings:{buffer:{window_samples:5,last_ms:20000,mean_ms:21000,p95_ms:24000},stt_execution:{window_samples:2,last_ms:6680,mean_ms:6900,p95_ms:7120},agent_to_first_send:{window_samples:1,last_ms:13000,mean_ms:null,p95_ms:13000}}}')
        await click('Atualizar')
        await expect(page.locator('#ryze-buffer')).to_have_value('17')
        await page.locator('#ryze-buffer').fill('61')
        await expect(page.get_by_role('button',name='Salvar buffer',exact=True)).to_be_disabled()
        await page.locator('#ryze-buffer').fill('0')
        await click('Salvar buffer')
        await expect(page.locator('[aria-labelledby="ryze-buffer-title"]')).to_contain_text('Buffer salvo: sem espera')
        await page.locator('#ryze-echo-transcripts').uncheck()
        await click('Salvar transcrições')
        await expect(page.locator('[aria-labelledby="ryze-transcription-title"]')).to_contain_text('sem enviar a transcrição automática')
        await tab('Métricas')
        await expect(page.locator('.ryze-timing-list li')).to_have_count(3)
        await expect(page.locator('.ryze-timings')).to_contain_text('6,7 s')
        await expect(page.locator('.ryze-timings')).to_contain_text('Sem medição')
        await page.evaluate('window.testTransport.maintenance_active=true')
        await page.clock.run_for(5500)
        await expect(page.get_by_text('Manutenção: novas mensagens aguardam na fila',exact=True)).to_be_visible()
        await page.evaluate('window.testTransport.maintenance_active=false')
        await page.clock.run_for(5500)
        await tab('Visão geral')
        await page.evaluate("window.testTransport.whatsapp_state='logged_out'")
        await page.clock.run_for(5500)
        await expect(page.locator('.ryze-channel')).to_contain_text('Sessão encerrada')
        await expect(page.locator('.ryze-channel-facts > div').first.locator('.ryze-dot')).to_have_class('ryze-dot is-muted')
        await page.evaluate("window.testTransport.whatsapp_state='connected'")
        await page.clock.run_for(5500)
        await tab('Configurações')
        await click('Pausar Hermes neste canal')
        await expect(page.get_by_role('status').filter(has_text='Canal pausado.')).to_be_visible()
        await click('Conta pessoal')
        await page.get_by_text('Trocar conta ou remover acesso local',exact=True).click()
        await page.locator('#ryze-forget').check()
        await click('Remover acesso local')
        await expect(page.get_by_role('heading',name='Conecte sua conta RyzeAPI')).to_be_visible()
        assert 'synthetic-token' not in await page.content()
        # Initial retry must hydrate saved fields, not defaults; no mutation while inspecting.
        seed = "window.testSeed({credential_saved:true,instance:'hermes-demo',allowed_users:'5511999999999',allowed_recipients:'5511999999999',buffer_seconds:20,echo_transcripts:false,enabled:true,webhook_configured:true});window.testConnected();window.testStateFailures=2"
        await load(seed)
        await click('Tentar novamente')
        await tab('Configurações')
        await expect(page.locator('#ryze-buffer')).to_have_value('20')
        await expect(page.locator('#ryze-echo-transcripts')).not_to_be_checked()
        await expect(page.get_by_role('checkbox',name='Comandar Hermes: 5511999999999')).to_be_checked()
        await page.evaluate("window.__HERMES_PLUGIN_SDK__.fetchJSON('/api/plugins/ryzeapi/instances',{method:'POST',body:JSON.stringify({name:'outra-instancia'})}).then(()=>window.testSeed({instance:'hermes-demo'}))")
        await click('Atualizar')
        await tab('Instâncias')
        mutations = await page.evaluate('window.testCalls.filter(c=>c.method==="POST").length')
        await page.locator('.ryze-instance-table tr').filter(has_text='outra-instancia').get_by_role('button',name='Ver detalhes').click()
        await expect(page.get_by_role('heading',name='outra-instancia')).to_be_visible()
        assert await page.evaluate('window.testCalls.filter(c=>c.method==="POST").length') == mutations
        await expect(page.locator('.ryze-title-row h2')).to_be_focused()
        review=Path(os.environ.get('RYZE_UI_REVIEW','/tmp/ryze-ui-review'));review.mkdir(parents=True,exist_ok=True)
        for name in ['Visão geral','Instâncias','Métricas','Configurações']:
            await tab(name)
            for width, height, suffix in [(1440,1000,'desktop'),(390,844,'mobile')]:
                await page.set_viewport_size({'width':width,'height':height})
                await page.evaluate('window.scrollTo(0,0)')
                assert await page.evaluate('document.documentElement.scrollWidth<=innerWidth'),(name,width)
                await page.screenshot(path=str(review/(str(['Visão geral','Instâncias','Métricas','Configurações'].index(name))+'-'+suffix+'.png')),full_page=True)
        assert not errors,errors
        print(json.dumps({'result':'PASS','network':'blocked','page_errors':errors,'scenarios':23,'screenshots':str(review)}))
        await browser.close()

if __name__ == '__main__': asyncio.run(main())
